### ISSUE TITLE
SQL error when querying on the UK Biobank data

### ISSUE THREAD

**Issue by Cruiseee** [hakyimlab/ukbrest#2]
Hi Milton,

The query on the sample data worked fine. I have tested on the sample data which you have provided and phenotype querying worked fine. But when I'm testing with real UK Biobank data I'm getting some SQL error (Please look at the screenshot 3). How can I solve this and can you explain to me where it is going wrong?

Thanks and regards.

![ukbrest_errors_3_edited](https://user-images.githubusercontent.com/36948814/63684044-9a4d3700-c819-11e9-9846-a48d1734f65f.png)
![ukbrest_errors_4_edited](https://user-images.githubusercontent.com/36948814/63684045-9a4d3700-c819-11e9-8c18-3248be8d2d5e.png)
![ukbrest_errors_5](https://user-images.githubusercontent.com/36948814/63684047-9ae5cd80-c819-11e9-8b8d-9ed74eb9f7b8.png)

**Comment by miltondp** [comment]
Hi Cruiseee,

Sorry for the delay in replying. I just tried the same query and worked for me. From the logs, looks like the loading phase found two files and loaded them successfully (first screenshot). However, it seems you didn't load the data-field 50 (height), which the cause of the error in the last screenshot ("column c50_0_0 does not exist").

Could please check the folder where you have your CSV files and make sure you have all files of your application? Also, make sure you have access to data-field 50. You can also follow [these steps](https://github.com/hakyimlab/ukbrest/wiki/SQL-schema) to check what you have in the PostgreSQL database.

Let me know if I can help with something else.

**Comment by Cruiseee** [comment]
Hi Milton,

Thanks for your reply and suggestion. It seems in the phenotype data I'm having, there is no height column. So, I'll change my query accordingly and get back to you.

**Comment by Cruiseee** [comment]
I changed the query and it worked. Thanks for your guidance.
